swagger: '2.0'
info:
  description: '.'
  version: '1.0.0'
  title: 'Armold template'
  contact:
    email: 'lucaslopezf@gmail.com'
tags:
  - name: 'country'
    description: 'Everything about your countries'
schemes:
  - 'https'
  - 'http'
paths:
  /country:
    get:
      tags:
        - 'country'
      summary: 'Finds countries with filter'
      description: ''
      produces:
        - 'application/json'
      parameters:
        - name: '_limit'
          in: 'query'
          description: 'Limit'
          required: false
          type: 'integer'
          format: 'int64'
        - name: '_page'
          in: 'query'
          description: 'Page'
          required: false
          type: 'integer'
          format: 'int64'
        - name: 'code'
          in: 'query'
          description: 'Country code'
          required: false
          type: 'string'
        - name: 'name'
          in: 'query'
          description: 'Country name'
          required: false
          type: 'string'
        - name: 'sort'
          in: 'query'
          description: 'Sort'
          required: false
          type: 'array'
          items:
            type: 'string'
            enum:
              - 'name'
            default: 'name'
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/ApiResponse'
        '400':
          description: 'Invalid status value'
        '404':
          description: 'Invalid status value'
definitions:
  Country:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      code:
        type: 'string'
        description: 'int64'
      name:
        type: 'string'
      states:
        type: 'array'
        items:
          type: 'object'
          $ref: '#/definitions/State'
  State:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      cities:
        type: 'array'
        items:
          type: 'object'
          $ref: '#/definitions/City'
  City:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      localities:
        type: 'array'
        items:
          type: 'object'
          $ref: '#/definitions/Locality'
  Locality:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
  ApiResponse:
    type: 'object'
    properties:
      limit:
        type: 'integer'
        format: 'int32'
      page:
        type: 'integer'
        format: 'int32'
      total:
        type: 'integer'
        format: 'int32'
      results:
        type: 'array'
        items:
          type: 'object'
          $ref: '#/definitions/Country'
